CI: Add release workflow
imperialCHEPI/healthgps-examples pull request #30
Opened 2024-09-27 09:53 UTC by alexdewar

This PR adds a release workflow to zip up each of the example models and upload them as release artifacts.

I also removed a couple of symlinks that were in the repo and replaced them with copies of the files they pointed to instead, because symlinks aren't guaranteed to work on Windows.

Closes #24.

2024-09-27 11:31 UTC, jamesturner246 requested changes
Looks good. Just the policy covariance comment below and all good.

2024-09-27 11:31 UTC, jamesturner246 commented on KevinHall_India/residual_policy_covariance.csv
I think the corresponding policy covariance file also needs copying into the root project folder, as you've done for `static_model.json`.

2024-09-30 06:51 UTC, alexdewar commented on KevinHall_India/residual_policy_covariance.csv
I actually changed the file path (L175), so the config file will still work. I double-checked that it is still loadable with HGPS.

2024-10-02 18:15 UTC, jamesturner246 approved these changes
Oh yes, so you have.. My bad. Looks good then! :+1:

2024-10-03 07:27 UTC, merged